# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b6616e0652c65c4c4d578cc6a0c7cabec2db66edbdba94a35bf9145b469cef299b9ed2bdbb32b5a9fdcf2343eb1d0e4ab18cbd08bd36cdb53e9c6c152be89df

test:
  secret_key_base: 87ef6d4ac3b8624c9c3ea00431fabffc6e3d54c87420d44833f386c3bd24d42d256eb8e8ed8a95cb77148fdac083f86e63ffb80d8cf984783401219b4bbf6279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
